// JavaPlayersOnTeamClaude.java
// Generated by Claude (Anthropic)
// Program: "Players on a Team" — recreate prior class assignment

import java.util.Scanner;

public class JavaPlayersOnTeamClaude {
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        // Sport data: name and roster size
        String[] sportNames = {"NFL Football", "NBA Basketball", "MLB Baseball", "NHL Hockey"};
        int[] rosterSizes = {53, 13, 25, 23};
        
        System.out.println("=== Players on a Team (Claude Version) ===");
        System.out.println();
        
        // Display menu and get sport selection
        int sportChoice = getSportChoice(scanner, sportNames);
        int expectedRoster = rosterSizes[sportChoice - 1];
        String selectedSport = sportNames[sportChoice - 1];
        
        System.out.println("You selected: " + selectedSport);
        System.out.println("Expected roster size: " + expectedRoster + " players");
        System.out.println();
        
        // Get current number of players
        int currentPlayers = getCurrentPlayers(scanner);
        
        // Calculate and display result
        System.out.println();
        displayRosterStatus(currentPlayers, expectedRoster);
        
        scanner.close();
    }
    
    private static int getSportChoice(Scanner scanner, String[] sportNames) {
        int choice = 0;
        boolean validInput = false;
        
        while (!validInput) {
            System.out.println("Select a professional sport:");
            for (int i = 0; i < sportNames.length; i++) {
                System.out.println((i + 1) + " - " + sportNames[i]);
            }
            System.out.print("Enter your choice (1-4): ");
            
            if (scanner.hasNextInt()) {
                choice = scanner.nextInt();
                scanner.nextLine(); // consume newline
                
                if (choice >= 1 && choice <= 4) {
                    validInput = true;
                } else {
                    System.out.println("Error: Please enter a number between 1 and 4.");
                    System.out.println();
                }
            } else {
                System.out.println("Error: Invalid input. Please enter a number.");
                scanner.nextLine(); // consume invalid input
                System.out.println();
            }
        }
        
        return choice;
    }
    
    private static int getCurrentPlayers(Scanner scanner) {
        int players = -1;
        boolean validInput = false;
        
        while (!validInput) {
            System.out.print("How many players are currently on the team? ");
            
            if (scanner.hasNextInt()) {
                players = scanner.nextInt();
                scanner.nextLine(); // consume newline
                
                if (players >= 0) {
                    validInput = true;
                } else {
                    System.out.println("Error: Number of players cannot be negative.");
                    System.out.println();
                }
            } else {
                System.out.println("Error: Invalid input. Please enter a whole number.");
                scanner.nextLine(); // consume invalid input
                System.out.println();
            }
        }
        
        return players;
    }
    
    private static void displayRosterStatus(int current, int expected) {
        if (current < expected) {
            int needed = expected - current;
            System.out.println("There are not enough players");
            System.out.println(needed + " more players are needed");
        } else if (current > expected) {
            int extra = current - expected;
            System.out.println("There are too many players");
            System.out.println(extra + " players need to be eliminated");
        } else {
            System.out.println("You have the correct number of players");
        }
    }
}
